rgzrgzm/e-commerce-pf

- client/package.json
Acá se colocan las dependencias para que el boilerplate quede con lo mínimo para utilizar Redux, react
> Dependencias esenciales Redux Router

- client/package-lock.json
- client/package.json
- client/src/App.jsx
- client/src/components/Admin/index.jsx
- client/src/components/Cart/index.jsx
- client/src/components/CreateUser/index.jsx
- client/src/components/CreateUser/styles.js
- client/src/components/Detail/index.jsx
- client/src/components/Landing/index.jsx
- client/src/components/Nav/index.jsx
- client/src/components/Profile/index.jsx
- client/src/main.jsx
- client/src/redux/reducer.js
- client/src/redux/store.js
Agregue el routing de front, quedan por armar el Admin-Hub donde el admin podra publicar productos, modificar precios/promociones/manejo de usuarios y ¿estadisticas?
detalle de producto, perfil de usuario, carrito de compra
> Martin  dev 

- server/README.md
Agregado un readme con las variables de entorno necesarias para la conexion de la db
> API readme

- server/src/models/assets/productos.json
Agregue el ejemplo que habia mencionado Emi. De que en cada producto, aparezca su categoria correspondiente
> refactored

- client/package-lock.json
- client/package.json
- client/src/components/Card/index.jsx
- client/src/components/PopUp/index.jsx
- client/src/components/PopUp/styles.js
--Incorpora tecnologia reactjs-popup--
Agrego proyecto de paso previo al Carrito, al hacer click en Add to Cart se inicia el pop up (cero estilizado por ahora) 
La idea es mostrar un poco la descripcion del objeto, ofrecer la posibilidad de agregar mas items y cuanto costaria ese agregado.
Se puede salir del pop up haciendo click por fuera de la zona amarilla (pienso un blureado oscuro a la home y el color del pop-up idem al home), haciendo click en el boton x superior o en seguir comprando.
Boton añadir agregaria los extras al carrito, boton cancelar cancelaria la incorporacion del producto por el cual se ingreso al pop up
> Martin shop cart

- server/src/routes/category.js
- server/src/routes/createProduct.js
- server/src/routes/editProduct.js
Adaptado el edit y create al nuevo formato de JSON. 
Category ahora permite crear categoría enviando una por body.
> Fix: Adaptado el edit y create al nuevo formato de JSON. 

- client/src/components/Nav/index.jsx
- client/src/components/Nav/search.jsx
se tiene en cuenta para no tener conflicto con el PO y no dejar vacíos que nos resten puntos en la presentación del lunes.
> Sin microfono & user para la Demo1

- client/src/App.jsx
- client/src/components/Card/index.jsx
- client/src/components/LeftBar/index.jsx
- client/src/components/LeftBar/styles.js
- client/src/containers/CardsContainer/index.jsx
- client/src/redux/actions/actionTypes.js
- client/src/redux/actions/product.js
- client/src/redux/reducers/product.js
> Feat: Options to organize the product items

- client/src/App.jsx
- client/src/components/Nav/index.jsx
- client/src/components/Nav/nav.module.css
- client/src/components/Nav/search.jsx
- client/src/components/Nav/style.js
- client/src/containers/CardsContainer/index.jsx
- client/src/containers/CardsContainer/styles.js
- client/src/containers/MainContainer/index.jsx
- client/src/pages/Detail/index.jsx
- client/src/redux/actions/product.js
- client/src/redux/reducers/product.js
- client/src/styles/appStyle.js
se puede utilizar con el filtrado y se colocaron con imagenes para facilitar la busqueda.
> Search Corregido para Redux y ser usado con los filtrados

- client/src/containers/CardsContainer/index.jsx
Fix: faltaba import de useDispatch
> Fix: Update index.jsx

- server/src/models/producto.js
- server/src/models/producto_talle.js
- server/src/routes/index.js
- server/src/routes/stock.js
Ahora se puede handlear el stock desde una ruta en el back.
> Admin stock back

- server/README.md
- server/src/routes/index.js
- server/src/routes/postRating.js
Documentación de casi toda la API. Los que estuvieron trabajando en el back deberían ver la parte del final que les dejé una lista de archivos de rutas que faltan documentar.
> API Documentation

- client/src/components/Card/index.jsx
- client/src/components/PopUp/index.jsx
- client/src/pages/Detail/index.jsx
- server/src/models/assets/productos.json
Agrego bloqueos para no agregar al carrito productos sin stock o stock insuficiente
> Control de stock

- client/src/components/Cart/OrderItem/index.jsx
- client/src/components/PopUp/index.jsx
- client/src/pages/Detail/index.jsx
- client/src/redux/actions/cart.js
- client/src/redux/reducers/cart.js
Reverts rgzrgzm/e-commerce-pf#69
> Revert "M dev"

- server/index.js
- server/src/db.js
- server/src/models/compra.js
- server/src/models/pedido.js
tambien crea usuarios y les encripta la pass
> db carga pedidos con usuario y productos asignados

- client/package-lock.json
- client/package.json
- client/src/App.jsx
- client/src/components/Card/index.jsx
Quité una ruta de confirmación la cual se intentaba importar pero no había ningún archivo.
Quité { postFavoritos } del componente card. Aparentemente no está en el actions esa funcion.
Hay que instalar la siguiente dependencia: react-data-table-component. Actualicé el package.json
Quite un CreateProduct que estaba duplicado.
> Arreglo de errores que impedian que se ejecute el client

- client/src/App.jsx
- client/src/containers/CartContainer/index.jsx
- client/src/pages/Admin/products.jsx
- client/src/pages/Checkout/Checkout.jsx
- client/src/pages/Checkout/checkout.module.css
- client/src/pages/Checkout/styles.js
- client/src/pages/CheckoutSuccess/CheckoutSuccess.jsx
- client/src/pages/CheckoutSuccess/CheckoutSuccess.module.css
- client/src/pages/CheckoutSuccess/styles.js
- client/src/redux/actions/actionTypes.js
- client/src/redux/actions/checkout.js
- client/src/redux/reducers/auth.js
- client/src/redux/reducers/checkout.js
- server/index.js
- server/src/controllers/user.controller.js
- server/src/db.js
- server/src/models/assets/usuarios.json
- server/src/models/datosFactura.js
- server/src/models/usuario.js
- server/src/routes/cargarFactura.js
- server/src/routes/checkout.js
- server/src/routes/createPedido.js
- server/src/routes/editarPedidoFactura.js
- server/src/routes/getPedidoId.js
- server/src/routes/index.js
- Refactor a el formulario de datos de facturacion y post pago. Ahora está acorde a los estilos generales de la app.
- Ahora el boton se bloquea al generar el boton de pago.
- Ahora se genera un pedido con estado "Pendiente de pago al generar la compra".
- Modifiqué un poco la ruta del back de crearPedidos. Ahora los talles no se mandan por id, si no por el talle en si (S, M, XL, etc)
- Modifiqué los datos del usuario que se guardan en el localStorage. Ahora son más completos. Esto me sirve para hacer el autocompletado del formulario. 
- Ahora solo se puede iniciar el proceso de pago si la sesion está iniciada. Caso contrario te manda a iniciar sesion.
-  Está incluido también al cambio al $ en el dashboard
----------------------------------------------------------------------------------- …
> Feat: Ahora se crean los pedidos de forma correcta

- client/src/components/Nav/index.jsx
- client/src/components/Nav/nav.module.css
- client/src/components/Nav/style.js
> Agregado iconos al Nav y un hover para indicar que se seleccionan

- client/index.html
- client/package-lock.json
- client/package.json
- client/src/main.jsx
- client/src/pages/Login/index.jsx
- client/src/pages/Login/styles.js
- client/src/redux/actions/autenticacion.js
Flujo de login completado en un 70%
se planea  hacer un login rapido por lo que se esta experimentando con la version de google https://github.com/MomenSherif/react-oauth. Se plantea sacarle provecho para un ingreso mas rapido.
> Redux usuarios login

- server/src/routes/createPedido.js
ya no puede haber -15 remeras xd
> fix de stock en el backend

- client/src/components/PopUp/index.jsx
- client/src/components/PopUp/styles.js
> no se selecciona el texto cuando añadimos cantidad de items al carrito

- client/src/containers/MainContainer/index.jsx
- client/src/pages/CreateUser/index.jsx
- client/src/pages/Login/index.jsx
- server/src/controllers/user.google.controller.js
- server/src/models/producto.js
- server/src/models/usuario.js
- server/src/routes/index.js
- server/src/routes/user.js
> flow register corregido 95%

- client/src/pages/CreateUser/index.jsx
- client/src/pages/CreateUser/styles.js
- server/src/controllers/user.google.controller.js
> flujo arreglado de register

- client/package-lock.json
- client/package.json
- client/src/components/Nav/index.jsx
- client/src/pages/CreateUser/index.jsx
- client/src/pages/CreateUser/styles.js
- server/src/controllers/user.google.controller.js
Se propone este btn de diseno se puede modificar por estilos mas globales quedo atento a las sugerencias o frente otros disenos.
https://user-images.githubusercontent.com/19938780/180040625-bfbe9fda-9f46-42a9-b56a-f534fc288080.mp4
> Btn dark light

- server/src/db.js
- server/src/models/assets/sucursales.json
- server/src/models/sucursales.js
Te acuerdas de JSON? volvió! en forma de fichas! 
Cree un Json con las sucursales
> sucursales

- server/package-lock.json
- server/package.json
- server/src/models/compra.js
- server/src/routes/createPedido.js
- server/src/routes/editarPedidoFactura.js
Ahora el stock se resta bien. Tuve que agregar una libreria que ponga los requests hechos en una cola para que no se ejecute simultaneamente el código de restar el stock y se valide todo bien para cuando hagan los req de crear pedidos y comprar, por lo que toca hacer npm i.
> Restar stock en pago

- client/src/App.jsx
- client/src/components/Nav/index.jsx
- client/src/redux/actions/autenticacion.js
Una vez la sesion el cerrado en las otras ventanas se cierra si lo detecta
> Sesion online bugFixed

- client/src/components/CreateProduct/form.jsx
se pueden subir imagenes para los productos a la nube y cargarlas en la pag
> product image upload con cloudinary

- client/src/pages/Detail/index.jsx
- client/src/redux/actions/actionTypes.js
- client/src/redux/actions/cart.js
- client/src/redux/reducers/cart.js
- server/src/controllers/user.google.controller.js
> await ahora si funciona

- client/src/components/CheckoutResume/resume.jsx
- client/src/components/CheckoutResume/resume.module.css
- client/src/components/Nav/nav.module.css
- client/src/pages/Admin/products.jsx
> Fix: Algunas cosas

- client/index.html
- client/package-lock.json
- client/package.json
- client/src/components/Card/styles.js
- client/src/components/CreateProduct/form.css
- client/src/components/CreateProduct/form.jsx
- client/src/components/CreateProduct/index.jsx
- client/src/components/DashboardAdmin/Dashboard.css
- client/src/components/DashboardAdmin/index.jsx
- client/src/components/EditProduct/form.css
- client/src/components/EditProduct/form.jsx
- client/src/components/EditProduct/index.jsx
- client/src/components/LeftBar/index.jsx
- client/src/components/Modal/Modal.css
- client/src/components/Modal/Modal.jsx
- client/src/components/RequireAuth/index.jsx
- client/src/pages/Checkout/Checkout.jsx
- client/src/pages/Checkout/checkout.module.css
- client/src/pages/Checkout/styles.js
- client/src/pages/CheckoutSuccess/CheckoutSuccess.jsx
- client/src/pages/CheckoutSuccess/CheckoutSuccess.module.css
- client/src/pages/CheckoutSuccess/styles.js
- client/src/redux/actions/checkout.js
- client/src/redux/reducers/checkout.js
- client/src/styles/GlobalStyles.js
- server/src/routes/createPedido.js
Puse un :hover para que muestre todo el texto al seleccionarla. Con margin-bottom: -2rem funciona sin afectar otros elementos.
> Feat: Ahora al hacer hover muestra todo el texto en las cards

- client/src/components/Toast/index.jsx
- client/src/pages/Profile/index.jsx
Modifique los placeholder en profile para que no quede "pepito perez" jajajaj
Modifique un alert para que se entienda mejor el mensaje
> change: Modifique los placeholder

- server/README.md
- server/index.js
Para setear el force en false al cargar la db hay que ir al .env y poner DEPLOYED=true.
Tambien si por alguna razon en el deploy se tiene que reiniciar la app, mientras haya mas de 0 productos y 0 talles en la db, la data no se vuelve a intentar insertar otra vez.
> pseudomigracion

- client/package-lock.json
- client/src/App.jsx
- client/src/components/ModalReview/Backdrop.jsx
- client/src/components/ModalReview/clickOutside.js
- client/src/components/ModalReview/index.jsx
- client/src/components/ModalReview/style.js
- client/src/components/RequireAuth/index.jsx
- client/src/components/Review/index.jsx
- client/src/components/Review/style.js
- client/src/containers/ListContainer/index.jsx
- client/src/containers/ListContainer/styles.js
- client/src/containers/MainContainer/index.jsx
- client/src/pages/Compras/index.jsx
- client/src/redux/actions/reviews.js
- server/package-lock.json
- server/package.json
- server/src/routes/getRatingProduct.js
- server/src/routes/postRating.js
Se completa el ciclo tanto back como front para hacer reviews. en el perfil
> Reseñas completado en perfil front back.

- client/src/pages/CheckoutSuccess/CheckoutSuccess.jsx
- client/src/redux/actions/checkout.js
- server/src/routes/confirmarCompra.js
- server/src/routes/editarPedidoFactura.js
> Se envian mails al terminar la compra

- client/src/App.jsx
- client/src/components/DashboardAdmin/index.jsx
- client/src/components/Favoritos/index.jsx
- client/src/components/Toast/styles.js
- client/src/containers/CardsContainer/index.jsx
- client/src/containers/CartContainer/index.jsx
- client/src/containers/CartContainer/styles.js
- client/src/containers/ListContainer/index.jsx
- client/src/containers/MainContainer/index.jsx
- client/src/pages/Admin/products.jsx
- client/src/pages/Admin/sales.jsx
- client/src/pages/Admin/styles.js
- client/src/pages/Admin/users.jsx
- client/src/pages/Cart/index.jsx
- client/src/pages/Detail/index.jsx
- client/src/pages/Favoritos/index.jsx
- client/src/redux/actions/cart.js
en hover el boton se pone verde
aca se  ve con hover, sin hover se ve con el azul de los botones de la pagina
aca con darkmode 
Se soluciona el problema hablado con el localStorage
> Alertas con dark mode

- client/src/components/DropDown/index.jsx
- client/src/components/DropDown/style.js
- client/src/components/Nav/index.jsx
> Corregido Sub menu ingreso registro

- client/src/components/ModalReview/index.jsx
- client/src/components/ModalReview/style.js
- client/src/components/Review/index.jsx
- client/src/components/Review/style.js
- client/src/containers/ListContainer/index.jsx
- client/src/pages/Checkout/Checkout.jsx
- client/src/pages/CreateUser/index.jsx
- client/src/pages/Detail/index.jsx
- client/src/pages/Login/index.jsx
- client/src/pages/Profile/styles.js
- client/src/styles/GlobalStyles.js
> Cambios de estilos

- client/src/components/Review/index.jsx
- client/src/components/Review/style.js
muchas ocaosdnsoadhasduiakgnoiwefudasfjkn
> Arreglos menores
